version: "3"

services:
  todo-list:
    container_name: todo-list
    build: ./
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    working_dir: /usr/src/DJANGO-TODO-LIST/TODO_List/
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./TODO_List:/usr/src/DJANGO-TODO-LIST/TODO_List/
